# Generated by Django 4.1 on 2022-08-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ner", "0002_remove_file_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
